### PR TITLE
Updates the workshop view page

### PR DESCRIPTION
**Pull request by harshasrikara**
Following updates:
 - canvasJS graph now displays aggregate values. Xaxis now shows numbering of each level (1,2,3,4....n), Yaxis now displays the total number of students that have progressed to that level
 - Workshop admin page now contains an individualized progress bar for each student which shows their name, their progress (green for completed, yellow for working on and red for tobe completed) as well as options to see if they have submitted an alert or not and to download their information

### CODE REVIEW

**Comment by harshasrikara** [comment]
Ya will look into that, I think the solution is to make the xAxis values Strings instead of ints

**Comment by aemmadi** [comment]
Also I recommend you follow the standard branch naming conventions.

`feature/name`
`fix/name`
`update/name`
`internal/name`

Its just a suggestion to follow the conventions but its fine if you don't. Just a heads up that all my branches will be named accordingly.

**Comment by harshasrikara** [comment]
> Also I recommend you follow the standard branch naming conventions.
> 
> `feature/name`
> `fix/name`
> `update/name`
> `internal/name`
> 
> Its just a suggestion to follow the conventions but its fine if you don't. Just a heads up that all my branches will be named accordingly.

Yah I can def do that going forward. Can you add that to the readme in your next commit under guidelines or perhaps a best practices section?

**Comment by aemmadi** [comment]
https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494

I highly suggest you don't delete any lock files. They help ensure everyone working on the project has the same version for all the sub dependencies.

**Comment by sivampatel** [comment]
Everything look good. Only thing I can think of is getting rid of the decimals on the y-axis as there is no need for them, but thats a small detail. With enough students, it should reconfigure on its own.

**Comment by harshasrikara** [comment]
> Everything look good. Only thing I can think of is getting rid of the decimals on the y-axis as there is no need for them, but thats a small detail. With enough students, it should reconfigure on its own.

Addressed all concerns, updated y Axis to only display integer values

**Pull request merged**
